name: Run NHK Scraper

on:
  schedule:
    - cron: '0 8 * * *' # Scheduled to run daily at 8 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Google Chrome (specific version)
      - name: Install Google Chrome
        run: |
          wget -N "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/linux64/chrome-linux64.zip"
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/google/chrome
          sudo ln -sf /opt/google/chrome/chrome /usr/bin/google-chrome
          rm -rf chrome-linux64.zip

      # Step 5: Install ChromeDriver (specific version)
      - name: Install ChromeDriver
        run: |
          wget -N "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          rm -rf chromedriver-linux64.zip chromedriver-linux64

      # Step 6: Run scraper
      - name: Run scraper
        run: python src/scraper.py
